#!/usr/bin/env python3
"""Fit the stage-1 geometry classifier from labelled events.

The node ships with hand-set priors so that a freshly flashed camera behaves
sensibly, but priors are not a model. Label events in the web interface, pull
the CSV, and refit against what this particular doorway actually looks like:

    curl -o dataset.csv http://<node>/api/dataset.csv
    python train_classifier.py dataset.csv > ../classifier_weights.h

Features are already normalised on the device (extractFeatures in detect.cpp),
so nothing is scaled here - the fitted weights stay in the same units as the
priors and remain readable as "how much does aspect ratio matter".

No third-party dependencies: plain gradient descent on the logistic loss with
L2 regularisation converges in well under a second on datasets of this size,
and requiring numpy to reproduce a build artefact is a poor trade.
"""

import csv
import math
import sys
from datetime import datetime, timezone

FEATURES = ["area", "fill", "aspect", "height", "centroid_y", "delta",
            "persistence", "global"]

EPOCHS = 4000
LR = 0.15
L2 = 1e-3


def load(path):
    rows_x, rows_y = [], []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            missing = [f for f in FEATURES if f not in row]
            if missing:
                sys.exit(f"column(s) missing from {path}: {', '.join(missing)}")
            label = row.get("label", "").strip()
            if label not in ("0", "1"):
                continue                      # unlabelled rows are not negatives
            rows_x.append([float(row[f]) for f in FEATURES])
            rows_y.append(int(label))
    return rows_x, rows_y


def fit(xs, ys):
    w = [0.0] * len(FEATURES)
    b = 0.0
    n = len(xs)
    for _ in range(EPOCHS):
        gw = [0.0] * len(FEATURES)
        gb = 0.0
        for x, y in zip(xs, ys):
            z = b + sum(wi * xi for wi, xi in zip(w, x))
            p = 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, z))))
            err = p - y
            for i, xi in enumerate(x):
                gw[i] += err * xi
            gb += err
        for i in range(len(w)):
            w[i] -= LR * (gw[i] / n + L2 * w[i])
        b -= LR * gb / n
    return w, b


def report(xs, ys, w, b, threshold=0.5):
    tp = fp = tn = fn = 0
    for x, y in zip(xs, ys):
        z = b + sum(wi * xi for wi, xi in zip(w, x))
        p = 1.0 / (1.0 + math.exp(-max(-30.0, min(30.0, z))))
        hit = p >= threshold
        if y == 1 and hit:
            tp += 1
        elif y == 1:
            fn += 1
        elif hit:
            fp += 1
        else:
            tn += 1
    acc = (tp + tn) / max(1, len(ys))
    return tp, fp, tn, fn, acc


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} dataset.csv > classifier_weights.h")

    xs, ys = load(sys.argv[1])
    if len(xs) < 20 or len(set(ys)) < 2:
        sys.exit(f"need at least 20 labelled rows of both classes, "
                 f"got {len(xs)} rows / {len(set(ys))} class(es)")

    w, b = fit(xs, ys)
    tp, fp, tn, fn, acc = report(xs, ys, w, b)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # These numbers are in-sample: the same events were used to fit and to
    # score. They say the fit converged, not that the model generalises.
    out = sys.stdout
    out.write("// Stage-1 logistic regression parameters.\n")
    out.write("//\n")
    out.write(f"// GENERATED by tools/train_classifier.py on {stamp}\n")
    out.write(f"// {len(xs)} labelled events ({sum(ys)} positive), in-sample "
              f"accuracy {acc*100:.1f}%\n")
    out.write(f"// confusion at 0.5: tp={tp} fp={fp} tn={tn} fn={fn}\n")
    out.write("//\n")
    out.write("// Feature order must match kFeatureNames[] in detect.cpp.\n")
    out.write("#pragma once\n\n")
    out.write('#include "app_config.h"\n\n')
    out.write("// Provenance string shown on the web interface, so an operator can tell a\n")
    out.write("// deployed node running priors from one running weights fitted on site.\n")
    out.write(f'#define CLASSIFIER_ORIGIN "fitted {stamp}, n={len(xs)}"\n\n')
    out.write(f"static const float kClassifierBias = {b:.4f}f;\n\n")
    out.write(f"static const float kClassifierWeights[FEATURE_COUNT] = {{\n")
    for name, wi in zip(FEATURES, w):
        out.write(f"    {wi:8.4f}f,  // {name}\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
